/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frontend/public/assets3d/gpu_rack.glb --output frontend/src/components/models/GPURack.tsx --draco --transform --types 
Files: frontend/public/assets3d/gpu_rack.glb [444.46KB] > C:\Users\Ojas\Desktop\ai-training-platform\frontend\src\components\models\gpu_rack-transformed.glb [1.05MB] (-137%)
*/

import * as THREE from 'three'
import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useHardwareTelemetry } from '../../hooks/useHardwareTelemetry'

export function GPURack(props: any) {
  const { nodes, materials } = useGLTF('/assets3d/gpu_rack.glb') as any
  const { mapGPUsToCards } = useHardwareTelemetry()
  const ledsRef = useRef<THREE.Mesh[]>([])

  useFrame(() => {
    const cards = mapGPUsToCards(8)
    for (let i = 0; i < 8; i++) {
        if (ledsRef.current[i]) {
            (ledsRef.current[i].material as THREE.MeshBasicMaterial).color.copy(cards[i].color)
        }
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group232992431.geometry} material={materials.PaletteMaterial001} position={[-0.02, -0.189, 0.157]} scale={1.06} />
      <mesh geometry={nodes.group747963819.geometry} material={materials.PaletteMaterial002} position={[0.005, -0.044, -0.148]} scale={0.855} />
      {/* Synthetic 8-GPU LED Status Array */}
      {Array.from({ length: 8 }).map((_, i) => (
        <mesh 
          key={i} 
          ref={(el) => (ledsRef.current[i] = el as THREE.Mesh)} 
          position={[0.2, 0.5 - i * 0.15, 0.45]} 
        >
            <sphereGeometry args={[0.02, 8, 8]} />
            <meshBasicMaterial color="#064e3b" />
        </mesh>
      ))}
    </group>
  )
}

useGLTF.preload('/assets3d/gpu_rack.glb')
